name: poke_poke_dex
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  like_button: ^2.0.4
  shimmer: ^3.0.0
  go_router: ^10.0.1
  graphql: ^5.0.0
  graphql_flutter: ^5.0.0
  hooks_riverpod: ^2.5.1
  path_provider: ^2.0.15
  isar: ^3.1.0
  isar_flutter_libs: ^3.1.0
  widgetbook_workspace:
    path: ./widgetbook/


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  graphql_codegen: ^0.12.2
  build_runner: ^2.4.11
  isar_generator:
    git:
      url: https://github.com/Kiruel/isar
      ref: fix/web_build
      path: packages/isar_generator
  melos: ^3.4.0

dependency_overrides:
  isar_generator:
    git:
      url: https://github.com/Kiruel/isar
      ref: fix/web_build
      path: packages/isar_generator

flutter:
  uses-material-design: true
  generate: true
