name: poke_poke_dex_flutter

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^5.0.0
  graphql: ^5.0.0
  graphql_flutter: ^5.0.0
  widgetbook: ^3.8.0
  widgetbook_annotation: ^3.1.0
  gql: ^0.14.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  graphql_codegen: ^0.12.2
  widgetbook_generator: ^3.0.0
  build_runner: ^2.4.11

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
