name: widgetbook_workspace
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '3.4.3'

dependencies:
  flutter:
    sdk: flutter
  graphql_flutter: ^5.0.1
  hooks_riverpod: ^2.5.1
  poke_poke_dex:
    path: ../
  widgetbook: ^3.8.0
  widgetbook_annotation: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  widgetbook_generator: ^3.8.0
  build_runner: ^2.4.11

flutter:
  uses-material-design: true
